name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  ci:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: 21
        distribution: temurin
        java-package: jdk
        architecture: x64
        check-latest: false
        server-id: github
        server-username: ${{ secrets.GITHUB_ACTOR }}
        server-password: ${{ secrets.GITHUB_TOKEN }}
        overwrite-settings: true

    - name: Set up PostgreSQL
      uses: Harmon758/postgresql-action@v1
      with:
        postgresql version: '15'
        postgresql db: testdb
        postgresql user: testuser
        postgresql password: testpass

    - name: Wait for PostgreSQL to be ready
      run: |
        for i in {1..10}; do
          pg_isready -h localhost -p 5432 -U testuser && break
          sleep 2
        done
        
    - name: Make Gradle wrapper executable
      run: chmod +x gradlew

    - name: Run tests with Gradle
      env:
        SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/testdb
        SPRING_DATASOURCE_USERNAME: testuser
        SPRING_DATASOURCE_PASSWORD: testpass
        SPRING_JPA_HIBERNATE_DDL_AUTO: update
      run: ./gradlew test

  deploy:
    name: Build and Deploy
    needs: ci
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: 21
        distribution: temurin
        java-package: jdk
        architecture: x64
        check-latest: false
        server-id: github
        server-username: ${{ secrets.GITHUB_ACTOR }}
        server-password: ${{ secrets.GITHUB_TOKEN }}
        overwrite-settings: true

    - name: Make Gradle wrapper executable
      run: chmod +x gradlew

    - name: Build with Gradle (skip tests)
      run: ./gradlew clean build -x test

    - name: Deploy to Render
      env:
        RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
      run: |
        curl -X POST \
          -H "Authorization: Bearer $RENDER_API_KEY" \
          -d '{}' \
          https://api.render.com/v1/services/dep-d00ktu8dl3ps73e43b3g/deploy
